---
- name: Playbook for stopping services
  hosts: al "{{host}}"
  become: yes
  become_method: sudo
  tasks:
    - name: stop apacheservice1
      when: ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7"
      systemd:
        name: "{{service1}}"
        state: stopped
      ignore_erros: true
    - name: stop apacheservice2
      when: ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7"
      systemd:
        name: "{{service2}}"
        state: stopped
      ignore_erros: true
    - name: stop apacheservice3
      when: ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7"
      systemd:
        name: "{{service3}}"
        state: stopped
      ignore_erros: true
    - name: stop apacheservice4
      when: ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7"
      systemd:
        name: "{{service4}}"
        state: stopped
      ignore_erros: true


    - name: stop apacheservice1
      when: ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "6"
      service:
        name: "{{service1}}"
        state: stopped
      ignore_erros: true
    - name: stop apacheservice2
      when: ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "6"
      service:
        name: "{{service2}}"
        state: stopped
      ignore_erros: true
    - name: stop apacheservice3
      when: ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "6"
      service:
        name: "{{service3}}"
        state: stopped
      ignore_erros: true
    - name: stop apacheservice4
      when: ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "6"
      service:
        name: "{{service4}}"
        state: stopped
      ignore_erros: true
