---
- name: Playbook for secgroups
  hosts: localhost
  gather_facts: no
  tasks: 
    - local_action:
        module: ec2_elb_lb
        state: present
        name: 'NewELB'
        security_group_ids: 'sg-123456, sg-67890'
        region: us-west-2
        subnets: "{{Web_subnet1.subnet.id}}"
        security_group_ids: "{{SecGroup.group_id}}"
        purge_subnets: yes
        listeners:
          - protocol: http
            load_balancer_port: 80
            instance_port: 80