---
- name: Playbook for secgroups
  hosts: localhost
  gather_facts: no
  tasks: 
    - name: create a VPC with dedicated tenancy and a couple of tags
      ec2_vpc_net:
        name: TaskVPC
        cidr_block: 10.10.0.0/16
        region: us-east-1
        tags:
          Class : Ansible
          Task: VPC