---
- name: Playbook for secgroups
  hosts: localhost
  tasks:
    - name: Create sec group1
      ec2_group:
        name: SecGroup
        description: Sec Group 1
        vpc_id: vpc-ebd1ac91
        region: us-east-1
        rules:
          - proto: tcp
            ports:
            - 80
            cidr_ip: 0.0.0.0/0